[project]
name = "struct-mark-docs-mcp"
version = "0.1.0"
description = "MCP to handle structured markdown documentation"
readme = "README.md"
authors = [
    { name = "Matteo Bortolotto", email = "yamatteo@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
struct-mark-docs-mcp = "struct_mark_docs_mcp:main"

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"
